[package]
name = "payroll_registry"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
payroll_events = { path = "../events" }
pause_manager = { path = "../pause_manager", default-features = false }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
pause_manager = { path = "../pause_manager", features = ["contract"] }

[features]
testutils = ["soroban-sdk/testutils"]
