name: Bug Report
description: Report a bug or unexpected behavior in ZK Payroll Contracts
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below as thoroughly as possible.
        Incomplete reports may be closed without investigation.

        > **Security note:** If this bug is a security vulnerability, **do not open a public issue**.
        > Instead, follow our [Security Policy](.github/SECURITY.md) for responsible disclosure.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Pre-flight Checklist
      description: Please confirm the following before submitting.
      options:
        - label: I have searched [existing issues](https://github.com/zkpayroll/zk-payroll-contracts/issues) and this is not a duplicate.
          required: true
        - label: I have read the [CONTRIBUTING.md](CONTRIBUTING.md) guide.
          required: true
        - label: I am running on the latest commit of `main`.
          required: true

  - type: dropdown
    id: affected-component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      multiple: true
      options:
        - payroll_registry
        - salary_commitment
        - proof_verifier
        - payment_executor
        - audit_module
        - token
        - ZK Circuit (Circom)
        - CI/CD Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: |
        What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide minimal, complete steps to reproduce the issue.
      placeholder: |
        1. Deploy contract with `stellar contract deploy ...`
        2. Call function `register_company(...)` with arguments `...`
        3. Observe error: `...`
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include full error output.
      render: shell
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Environment Information"

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "e.g. rustc 1.78.0 (9b00956e5 2024-04-29)"
    validations:
      required: true

  - type: input
    id: soroban-cli-version
    attributes:
      label: Soroban CLI Version
      description: Output of `soroban --version`
      placeholder: "e.g. soroban 21.0.0"
    validations:
      required: true

  - type: input
    id: stellar-cli-version
    attributes:
      label: Stellar CLI Version
      description: Output of `stellar --version`
      placeholder: "e.g. stellar 21.0.0"
    validations:
      required: false

  - type: input
    id: circom-version
    attributes:
      label: Circom Version (if circuit-related)
      description: Output of `circom --version`. Leave blank if not circuit-related.
      placeholder: "e.g. circom compiler 2.1.8"
    validations:
      required: false

  - type: input
    id: snarkjs-version
    attributes:
      label: snarkjs Version (if circuit-related)
      description: Output of `snarkjs --version`. Leave blank if not circuit-related.
      placeholder: "e.g. 0.7.3"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Your OS and version.
      placeholder: "e.g. Ubuntu 22.04 / macOS 14.4 / Windows 11"
    validations:
      required: true

  - type: input
    id: network
    attributes:
      label: Stellar Network
      description: Which network did you encounter this on?
      placeholder: "e.g. Testnet / Mainnet / Local (standalone)"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other context, logs, transaction hashes, contract IDs, or screenshots.
        For ZK-related bugs, include proof generation parameters and the circuit name.
    validations:
      required: false
