// scripts/generate_soroban_vk.js
// Parses verification_key.json and outputs Rust array structs for Soroban FFI

const fs = require('fs');
const path = require('path');

const vkPath = path.join(__dirname, '../circuits/verification_key.json');
const outputPath = path.join(__dirname, '../circuits/verification_key_soroban.rs');

function toRustArray(name, arr) {
    let flat = arr.flat(Infinity);
    let typeHint = typeof flat[0] === 'string' ? '&str' : 'u8';
    let values = flat.map(x => typeof x === 'string' ? `"${x}"` : x).join(', ');
    return `pub const ${name}: [&'${typeHint}; ${flat.length}] = [${values}];`;
}

function main() {
    if (!fs.existsSync(vkPath)) {
        console.error('verification_key.json not found:', vkPath);
        process.exit(1);
    }
    const vk = JSON.parse(fs.readFileSync(vkPath, 'utf8'));
    let rust = '// Auto-generated by generate_soroban_vk.js\n';
    for (const [key, value] of Object.entries(vk)) {
        if (Array.isArray(value)) {
            rust += toRustArray(key.toUpperCase(), value) + '\n';
        } else if (typeof value === 'string' || typeof value === 'number') {
            rust += `pub const ${key.toUpperCase()}: &str = "${value}";\n`;
        }
    }
    fs.writeFileSync(outputPath, rust);
    console.log('Rust FFI file written to', outputPath);
}

main();
