[package]
name = "shared_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { version = "=20.5.0", features = ["testutils"] }

[dev-dependencies]
soroban-sdk = { version = "=20.5.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
